### ISSUE TITLE
previous_match verb missing?

### ISSUE THREAD

**Issue by wolfisberg** [Canop/broot#377]
**Did a discussion occur before?**
No, either I didn't understand the miau chat or there was nobody there.

---

I'm on version 1.2.9 and I can't seem to find a verb (*previous_match* seems obvious) to traverse the match list backwards.

I found this [PR](https://github.com/Canop/broot/pull/63), which supposedly fixed this. This code snippet mentions the **BackTab** key

```
            KeyEvent::Char('\t') => {
                self.action = Action::Next;
            }
            KeyEvent::BackTab => {
                self.action = Action::Previous;
            }
```

which I have no idea what it is supposed to be. Shift-tab does not work for me and a verb that would allow me to bind another shortcut (preferable *ctrl-p*) is not mentioned in the help. I tried `previous_match` but that did not work.

I'm not sure if I am missing something or this is a bug.

Any Help is appreciated.

**Comment by Canop** [comment]
I've fixed a problem in which `:previous_match` didn't select only direct matches.
To add a shortcut, add an entry like this one in your verb lst:

		{
			key: F3
			internal: previous_match
		}

**Comment by wolfisberg** [comment]
This binding does at least something, but It behaves like :line_up. I guess that is what you fixed? Is your fix already in version 1.2.9?

```	
{
		key: F3
		internal: previous_match
}
```

Plus, the verb is missing from the help (?) menu.

Thanks for the effort!

**Comment by Canop** [comment]
Yes, that's what I fixed. It's not yet released, you must build broot from source or wait a few days for an official release.

**Comment by wolfisberg** [comment]
Ah, very cool. Thank you!

**Comment by Canop** [comment]
This is now in 1.3.1

**Comment by lepotic** [comment]
Works fine, but is still missing from the help, unless you know it exists and map it to a key. (Even then, the "name" column is empty, and it has no description.)
Other verbs were listed even though they were not mapped to any key.
```
┌────────────────────┬────────┬────────────────┬──────────────────────────────────────────────────────┐
│        name        │shortcut│      key       │                     description                      │
├────────────────────┼────────┼────────────────┼──────────────────────────────────────────────────────┤
│                    │        │    BackTab     │:previous_match                                       │
│  close_panel_cancel│        │BackTab, ctrl-w │close the panel, not using the selected path          │
│          next_match│        │      Tab       │select the next match                                 │

```
And I couldn't find a way to make it work via BackTab. The above mapping just doesn't work.
I don't know what my terminal (st) sends on Shift-Tab, but other commands recognize it (e.g., fzf).

**Comment by Canop** [comment]
Non mapped internals aren't listed in the help because they're not even usable most of the time and some of them are very niche. There's a complete list at https://dystroy.org/broot/conf_verbs/#internals

**Comment by lepotic** [comment]
@Canop Thanks for 92395cb, much appreciated!

**Comment by Canop** [comment]
@lepotic I now realize I overlooked some parts of your previous comments. This happens way too often and is bound to be even more frequent as I manage more FOSS projects after work that what my brain can support. Don't hesitate to visit the chat when you suspect I didn't understood you.
