### ISSUE TITLE
*WezTerm* supports the *Kitty* Image protocol now

### ISSUE THREAD

**Issue by stevenxxiu** [Canop/broot#473]
Per https://github.com/wez/wezterm/issues/986, *WezTerm* now supports the *Kitty* image protocol.

The code at https://github.com/Canop/broot/blob/424023b4b084e071ecf67fc719db56ce40a01345/src/kitty/image_renderer.rs#L87 only checks for `if term_name.contains("kitty")`. This can include *WezTerm* now too.

**Comment by Canop** [comment]
Thanks.
I'll have a look.

**Comment by Canop** [comment]
There's more to the problem than just detecting support.
I've implemented (presumed) correct protocol detection (see https://github.com/Canop/xterm-query) but for now I can't render the images the same way. I'll try to investigate more in the next days.

**Comment by wez** [comment]
I made a comment over here: https://github.com/Canop/broot/commit/0b15aede22d52d1f3a0fdf74e2e70ce4cd349f29#r62986264 about detection

> Kitty's spec specifies that _"The image will be scaled (enlarged/shrunk) as needed to fit the specified area"_ and Wezterm doesn't seem to respect that.

For the scaling issue, can you clarify for me what's happening? Are you using the `c` and `r` keys to set the desired columns and rows for the image?

https://github.com/Canop/broot/blob/master/src/kitty/image_renderer.rs#L192-L199

**Comment by dankamongmen** [comment]
> I've also another problem: the only way to correctly detect the support without having problems on some terminals seems to be to read an env var and there's no guarantee wezterm sets it in an adequate way.

i can tell you that Notcurses is detecting it via terminal query

**Comment by dankamongmen** [comment]
> i can tell you that Notcurses is detecting it via terminal query

https://github.com/dankamongmen/notcurses/blob/master/src/lib/in.c#L1243-L1250
https://github.com/dankamongmen/notcurses/blob/master/src/lib/in.c#L1563
https://github.com/dankamongmen/notcurses/blob/master/src/lib/termdesc.c#L470-L481

**Comment by wez** [comment]
I've fixed the scaling issue in wezterm!

**Comment by Canop** [comment]
I confirm the fix is working :)

![image](https://user-images.githubusercontent.com/617006/148339505-4c8b1aef-6cf1-4b7e-9f32-40a5832b76d1.png)

**Comment by Canop** [comment]
@wez Has there been a release since your fix ? 

Please see https://github.com/Canop/broot/issues/509

**Comment by wez** [comment]
Not yet; they can use the nightly build for now

**Comment by namespaceYcZ** [comment]
What's the progress now? I found image rendering still not "full quality" on the nightly wezterm and the newest broot(on Windows).
