### ISSUE TITLE
Question: is it possible to override/configure action of the <enter> key ? Or the open action ?

### ISSUE THREAD

**Issue by gotcha** [Canop/broot#65]
I tried 

 ```
[[verbs]]
name = "open"
invocation = "open"
shortcut = "<enter>"
execution = "vim {file}"
```
But did not succeed.

**Comment by Canop** [comment]
Override the <enter> key would be too complex as there are many cases.

Right now, you can make <enter> (and <alt-enter>) open your editor of choice by configuring xdg-open (on linux) to open text files with nvim. That's what I do.

It's much better than just having configured "open" because it takes into account the type and, for example, open your images in a more suitable application than vi.

This probably solves your problem. The rest of this comment is for the case it doesn't.

---

It's not a perfect solution for everybody as it opens nvim *in a new terminal*. This is quite good when doing <enter> (assuming you configured your terminal to open full-screen) but maybe not what you'd want when you use <alt-enter> (which closes br).

If you want a solution opening your text files in nvim on <enter> in the same terminal, then an evolution of broot would be necessary but the specs of the configuration aren't so obvious (to me).

**Side note:** I find the current situation quite good for my uses, with both the configuration xdg-open and using `:e` to open the selected file in nvim in the current terminal with the standard broot configuration and the global $EDITOR env variable set to /usr/bin/nvim.

**Comment by ghuls** [comment]
I also want to reassign the enter key to open the file in a text editor.
The `xdg-open` way won't work as I run broot on a server with not GUI.

**Comment by Canop** [comment]
The actions done on files with `<enter>` and `<alt>-<enter>` are the ones of the opener crate, which mostly uses xdg-open on unix. I should probably make this configurable.

Right now the workaround is to configure your own verb and for example do `:e` when you want to replace broot with your terminal editor.

**Comment by ghuls** [comment]
Now running `<enter>` on the server gives this:
```
$ br 
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:999:5

# Pressing middle mouse button printw now weird characters
$ 0;46;23M32;44;23M32;41;23M32;33;22M32;25;22M32;24;22M32;17;21M32;16;21M32;15;21M32;14;21M32;13;21M32;12;21M32;11;21M32;10;21M32;4;21M32;3;21M32;2;21M32;1;21M0;1;21m2;74;16M2;74;16m
```

**Comment by Canop** [comment]
I'm working on this.

**Comment by ghuls** [comment]
Just in case you need more info.

Pressing mouse buttons after a crash of broot gives slightly different codes.
The only way to get to get the mouse working is to press `SHIFT` together with clicking (similar to get normal mouse behaviour working when in vim VISUAL selection mode).
```
$ echo "Left mouse button: 0;141;54M0;141;54m"
Left mouse button: 0;141;54M0;141;54m
$ echo "Middle mouse button: 1;142;55M1;142;55m"
Middle mouse button: 1;142;55M1;142;55m
$ echo "Right mouse button: 2;142;55M2;142;55m"
"Right mouse button: 2;142;55M2;142;55m"

$ echo "Left mouse button: 0;108;51M0;108;51m"
Left mouse button: 0;108;51M0;108;51m
$ echo "Left mouse button: 0;111;51M0;111;51m"
Left mouse button: 0;111;51M0;111;51m
$ echo "Left mouse button: 0;120;52M0;120;52m"
Left mouse button: 0;120;52M0;120;52m
 $ echo "Middle mouse button: 1;120;52M1;120;52m"
Middle mouse button: 1;120;52M1;120;52m
$ echo "Middle mouse button: 1;138;52M1;138;52m"
Middle mouse button: 1;138;52M1;138;52m
$ echo "Middle mouse button: 1;138;52M1;138;52m"
Middle mouse button: 1;138;52M1;138;52m
$ echo "Middle mouse button: 1;150;51M1;150;51m"
Middle mouse button: 1;150;51M1;150;51m
$ echo "Right mouse button: 2;151;51M2;151;51m"
Right mouse button: 2;151;51M2;151;51m
$ echo "Right mouse button: 2;150;51M2;150;51m"
Right mouse button: 2;150;51M2;150;51m
$ echo "Right mouse button: 2;153;52M2;153;52m"
Right mouse button: 2;153;52M2;153;52m
```

**Comment by ghuls** [comment]
any update on this?

**Comment by Canop** [comment]
@ghuls All the weird characters problems are expected to disappear (or change) in a few days.

I've rewritten a lot of broot and termimad (used by broot) and contributed to crossterm in order to ~~gain a free tshirt~~ improve terminal usage (btw broot will run 100% on stderr and it will be possible to do things like `cd "$(broot)"`).

**Comment by Canop** [comment]
@ghuls I've released broot v0.10.0.
Tell me if you see any weird characters.

**Comment by ghuls** [comment]
I am trying to open `CHANGELOG.MD` of broot (with `Enter`) with broot 0.1.0.
After the panic, pressing mouse buttons still enters weird characters. After running `reset` in the terminal, everything works fine again.

```
├──rustfmt.toml
├──src
│  ├──app.rs
│  ├──app_context.rs
│  ├──browser_states.rs
│  └──35 unlisted
└──website
   ├──custom_theme …
   ├──docs …
   ├──mkdocs.yml
   └──README.md
   Hit <enter> to open the file, <alt><enter> to open and quit, or type a space then a verb
                                                                                      h:n   gi:athread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ExitStatus { cmd: "xdg-open (internal)", status: ExitStatus(ExitStatus(768)), stderr: "sh: line 881: www-browser: command not found\nsh: line 881: links2: command not found\nsh: line 881: elinks: command not found\nsh: line 881: links: command not found\nsh: line 881: lynx: command not found\nsh: line 881: w3m: command not found\nxdg-open: no method available for opening \'/ddn1/vol1/staging/leuven/stg_00002/lcb/ghuls/software/broot/CHANGELOG.md\'\n" }', src/libcore/result.rs:999:5
                                                                              note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
                                                            thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:999:5
$ 0;61;20M0;61;20m^C
```

**Comment by Canop** [comment]
@ghuls Broot is now in version 0.10.4
Can you confirm the problem doesn't exist anymore ?

**Comment by ghuls** [comment]
@Canop Unfortunately, the problem is still there with 0.10.4

**Comment by ghuls** [comment]
Just in case that you missed it before mouse clicks do to produce those weird key code when `SHIFT` is pressed:

> The only way to get to get the mouse working is to press SHIFT together with clicking (similar to get normal mouse behaviour working when in vim VISUAL selection mode).

The latest patch (`replace the "opener" crate with the "open" on`) fixes it (as broot does not crash anymore).

**Comment by Canop** [comment]
@ghuls I just pushed a new version (not released) which aims at solving all this. You'll still be  able to reopen or create another issue if it doesn't...
